modLoader = "javafml"
loaderVersion = "[0,)"
license = "MIT"
issueTrackerURL="https://ptms76/AdditionalSmallStairsArc/issues"

[[mods]]
modId = "additionalsmallstairs"
version = "${version}"
displayName="AdditionalSmallStairs"
logoFile = "icon.png"
authors = "Pitan"
description = '''

'''

[[dependencies.additionalsmallstairs]]
modId = "neoforge"
mandatory = true
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.additionalsmallstairs]]
modId = "minecraft"
mandatory = true
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.additionalsmallstairs]]
modId = "mcpitanlib"
mandatory = true
versionRange = "[2.0.0,)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.additionalsmallstairs]]
modId="smallstairs"
mandatory=true
versionRange="[1.0.0,)"
ordering="NONE"
side="BOTH"

